Implement the payments database boundaries and functions
kommitters/mintacoin pull request #105
Opened 2022-10-28 19:30 UTC by jhonatan-kmt

## Description

Create the payments schema and database functions 

Closes #93 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-31 22:04 UTC, SanGeeky requested changes

2022-11-01 15:47 UTC, SanGeeky commented on lib/mintacoin/payments/payment.ex
> +    |> cast(changes, [:status])
I think is also necessary, the field `:successful`,  in case of a failed transaction.

2022-11-01 15:48 UTC, SanGeeky reviewed
LGTM :sunrise_over_mountains:

2022-11-01 16:02 UTC, jhonatan-kmt commented on lib/mintacoin/payments/payment.ex
> +    |> cast(changes, [:status])
Ok, we will add it

2022-11-02 00:40 UTC, SanGeeky approved these changes
:rocket:

2022-11-02 19:24 UTC, merged