Implement the payment creation with the Stellar SDK
kommitters/mintacoin pull request #108
Opened 2022-11-02 21:11 UTC by juanm-roa

## Description

Implements the Payment between accounts in the stellar blockchain using the Stellar SDK.
Closes #95 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-04 21:37 UTC, SanGeeky requested changes
This implementation is amazing! I left some minor changes and a question

2022-11-04 21:37 UTC, SanGeeky commented on lib/mintacoin/payments/crypto/stellar.ex
> +    signatures = [master_signature, source_signature]
@juanm-roa @Odraxs why are you using the master account for this operation?

2022-11-04 21:37 UTC, SanGeeky commented on lib/mintacoin/payments/crypto/stellar.ex
> +      signature: source_signature
@juanm-roa @Odraxs IMO is better to use more descriptive variables, for example

- `source_secret_key`
- `destination_primary_key`

WDYT?

2022-11-04 22:19 UTC, miguelnietoa commented on lib/mintacoin/payments/crypto.ex
> +  @behaviour Mintacoin.Payments.Crypto.Spec
Hello guys! @juanm-roa @Odraxs  👋🏻 
ℹ️  This is a useful resource to keep in mind: https://github.com/christopheradams/elixir_style_guide#module-attribute-ordering

2022-11-07 21:07 UTC, juanm-roa commented on lib/mintacoin/payments/crypto/stellar.ex
> +    signatures = [master_signature, source_signature]
We used the master account because this is who pays the transaction fee. The signature of MA is used to sign the transaction and the Lumens(Native) are discounted from its balance.

2022-11-07 21:14 UTC, juanm-roa commented on lib/mintacoin/payments/crypto/stellar.ex
> +      signature: source_signature
Ok OMW!

2022-11-07 21:25 UTC, SanGeeky commented on lib/mintacoin/payments/crypto/stellar.ex
> +    signatures = [master_signature, source_signature]
That is correct! Besides as is demonstrated in your implementation the `source_signature` is used to authorize the payment from the source account.

2022-11-07 21:29 UTC, SanGeeky approved these changes

2022-11-07 21:31 UTC, merged