97 payment worker aggregate functions
kommitters/mintacoin pull request #116
Opened 2022-11-08 23:18 UTC by Odraxs

## Description

Payment worker who registers the transaction on the blockchain, sends the payment request, and updates the balances of the source and destination accounts

Closes #97 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-11-10 20:00 UTC, einerzg requested changes
@Odraxs 👀

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/payments.ex
> +    if Decimal.negative?(difference) do
use `case`

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/workers/create_payment.ex
> +         {:ok, %{successful: true} = tx_response},
this line doesn't look great here. Just it's a comment, maybe we need a refactor in this and other modules @CristhianRodriguezMolina, low priority.

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/workers/create_payment.ex
> +         payment_id
fix the order. 
```
blockchain_id,
payment_id,
_asset_id,
_amount,
_source_wallet_id,
_destination_wallet_id
```

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/workers/create_payment.ex
> +    {:ok, %{source_balance: source_balance, destination_balance: destination_balance}}
I'm not sure if in all cases an ok is always received 🤔. you should use a `with`

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/workers/create_payment.ex
> +      |> create_blockchain_tx(
`update_payment_status/1` can return an error, it's ready for that `create_blockchain_tx/7`

2022-11-10 20:00 UTC, einerzg commented on lib/mintacoin/payments/workers/create_payment.ex
> +      )
move this to a new function and use it `with` for validate the returns

2022-11-10 21:43 UTC, CristhianRodriguezMolina commented on lib/mintacoin/payments/workers/create_payment.ex
> +      )
@einerzg I think that we shouldn't use a with here, because that is defensive programming, and in order to fix any error that appears in the worker we should let it crash, in this way we can review later and know exactly where and why the error is happening. For that reason, I think is necessary to remove the `with` surrounding this block of code.

2022-11-10 21:46 UTC, CristhianRodriguezMolina commented on lib/mintacoin/payments/payments.ex
> +  def create_db_record(params) do
It is not being used in other modules, is public only for testing it.

2022-11-11 13:54 UTC, einerzg approved these changes

2022-11-11 17:18 UTC, miguelnietoa approved these changes

2022-11-11 19:09 UTC, merged