123 Implement create account consumer
kommitters/mintacoin pull request #124
Opened 2022-07-11 22:35 UTC by CristhianRodriguezMolina

## Description

Fixes #123

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-12 20:59 UTC, juanhurtado10 requested changes

2022-07-12 20:59 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/events/consumer.ex
> +    end
@CristhianRodriguezMolina @miguelnietoa this code needs a refactor guys, it is really hard to understand. Please, use functions.

2022-07-12 20:59 UTC, juanhurtado10 commented on apps/mintacoin/mix.exs
> +      {:mock, "~> 0.3.0", only: :test}
@CristhianRodriguezMolina @miguelnietoa why not use an elixir behavior and test implementations instead of adding a dependency to implement a mock?

2022-07-13 14:10 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/events/consumer.ex
> +    end
Okay, let's organize it better! Thanks 💯

2022-07-13 19:25 UTC, juanhurtado10 approved these changes

2022-07-13 19:26 UTC, merged