Implement the accounts database boundaries and functions
kommitters/mintacoin pull request #19
Opened 2022-09-12 16:56 UTC by FelipeGuzmanSierra

## Description

Create the accounts schema and database functions to allow creating an account, retrieve by the address, and recover the signature based on the 12 entropy words.

Closes #11 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-09-12 19:53 UTC, CristhianRodriguezMolina requested changes

2022-09-12 19:53 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/accounts.ex
> +  def retrieve(_address), do: {:error, :not_found}
@FelipeGuzmanSierra @jhonatan-kmt if the registry is not found, that is not really an error. If the registry doesn't exist we should return something like `{:ok, nil}`, and if the address is not a binary we can return something like `{:error, :invalid_address}`

2022-09-12 19:53 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/accounts.ex
> +      _error -> {:error, :bad_argument}
Same here, in order to not make a big mapping of the errors, we can review the naming of the errors, what do you think?

2022-09-12 21:18 UTC, CristhianRodriguezMolina requested changes

2022-09-12 21:18 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/accounts.ex
> +      error -> error
@jhonatan-kmt @FelipeGuzmanSierra Yoy can remove the `else`, by default the `with` returns any error within it.

2022-09-12 21:18 UTC, CristhianRodriguezMolina commented on test/mintacoin/accounts/accounts_test.exs
> +      {:error, :mnemonic_seed_words_error} =
@FelipeGuzmanSierra @jhonatan-kmt I think we can change this error name to something like `invalid_seed_words`, what do you think?

2022-09-12 21:22 UTC, juanhurtado10 commented on lib/mintacoin/accounts/accounts.ex
> +  rescue
@jhonatan-kmt IMO, a better approach would be to use `get_by/3`and avoid rescue clauses.

2022-09-13 15:15 UTC, CristhianRodriguezMolina commented on test/support/accounts/accounts_factory.ex
> +        {:ok, encrypted_signature} = Cipher.encrypt(signature, entropy)
@jhonatan-kmt @FelipeGuzmanSierra I think we should use here the `account_signature` instead of the `signature`, in order to use the one from the `attrs` if exist.

2022-09-13 15:18 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/accounts.ex
> +  end
@jhonatan-kmt @FelipeGuzmanSierra IMO, we can use here the single line notation:

```suggestion
  def retrieve(address) when is_binary(address), do: {:ok, Repo.get_by(Account, address: address)}
```

2022-09-13 15:23 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/accounts.ex
> +  @type error :: Changeset.t() | :not_found | :decoding_error | :bad_argument
@jhonatan-kmt @FelipeGuzmanSierra Here we have missed the `:invalid_address` error type from line 27, and the `:invalid_seed_words` type error from the function of line 33.

2022-09-13 15:51 UTC, CristhianRodriguezMolina approved these changes
Good job guys :100:

2022-09-13 15:55 UTC, merged