Implement the blockchains database boundaries and functions
kommitters/mintacoin pull request #20
Opened 2022-09-13 20:21 UTC by FelipeGuzmanSierra

## Description

Create the blockchains schema and database functions.

Closes #15 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-13 22:46 UTC, CristhianRodriguezMolina requested changes

2022-09-13 22:46 UTC, CristhianRodriguezMolina commented on lib/mintacoin/blockchains/blockchains.ex
> +  def create(name, network) when name in @networks and network in @network_types do
@jhonatan-kmt @FelipeGuzmanSierra In order to avoid this validation here, the `handle_response` function, and allow the `email` and `network` to be strings, IMO, we can let the validation to the schema. Also, it would be better to receive a `changes` map instead of the name and network separately.

2022-09-13 22:46 UTC, CristhianRodriguezMolina commented on lib/mintacoin/blockchains/blockchains.ex
> +      when name in @networks and network in @network_types do
Also here, to allow `email` and `network` to be strings this validation can be done in another way, for example, using `EctoEnum` with the `valid_value?/1` function.

> https://github.com/gjaldon/ecto_enum

2022-09-13 22:46 UTC, CristhianRodriguezMolina commented on priv/repo/migrations/20220912204927_create_blockchains.exs
> +      add(:name, :string, null: false, unique: true)
@FelipeGuzmanSierra @jhonatan-kmt IMO we can remove the `unique` here, because the unique index is already validating that the `:name` and the `:network` are unique together.

2022-09-13 22:46 UTC, CristhianRodriguezMolina commented on test/support/blockchains/blockchain_factory.ex
> +        blockchain_network = Map.get(attrs, :network, Enum.random(network_types))
@jhonatan-kmt @FelipeGuzmanSierra IMO we should remove the random here to avoid ambiguity in the creation of blockchains.

2022-09-14 16:10 UTC, CristhianRodriguezMolina requested changes

2022-09-14 16:10 UTC, CristhianRodriguezMolina commented on lib/mintacoin/blockchains/blockchains.ex
> +  @type error :: Changeset.t() | :invalid_params | :duplicated_registry | :not_found
@jhonatan-kmt @FelipeGuzmanSierra I think we can remove the error `:duplicated_registry` because now we are not using it.

2022-09-14 16:33 UTC, FelipeGuzmanSierra commented on lib/mintacoin/blockchains/blockchains.ex
> +  rescue
@CristhianRodriguezMolina agrees it's a good idea to have a default parameter for the network param in the retrieve function, it is easier for the user. We are going to add it!

2022-09-14 19:28 UTC, CristhianRodriguezMolina approved these changes
Good job guys :rocket:

2022-09-14 20:21 UTC, merged