Implement the wallets database boundaries and functions
kommitters/mintacoin pull request #24
Opened 2022-09-14 21:13 UTC by jhonatan-kmt

## Description

Create the wallets schema and database functions that allow creating a wallet, retrieved by the id and public_key

Closes #17 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-14 23:14 UTC, CristhianRodriguezMolina requested changes

2022-09-14 23:14 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/wallet.ex
> +    timestamps()
@FelipeGuzmanSierra @jhonatan-kmt Please add a virtual field to return the `secret_key` when creating the wallet.

2022-09-14 23:14 UTC, CristhianRodriguezMolina commented on test/mintacoin/accounts/wallets_test.exs
> +  alias Ecto.Changeset
@FelipeGuzmanSierra @jhonatan-kmt I think this can look better like this:
```suggestion
  alias Ecto.{Changeset, Adapters.SQL.Sandbox}
```

2022-09-14 23:14 UTC, CristhianRodriguezMolina commented on test/mintacoin/accounts/wallets_test.exs
> +        })
@FelipeGuzmanSierra @jhonatan-kmt To test all the fields, IMO. here we can send an empty map:

```suggestion
      {:error,
  %Changeset{
   errors: [
     public_key: {"can't be blank", _detail},
     encrypted_secret_key: {"can't be blank", _detail},
     account_id: {"can't be blank", _detail},
     blockchain_id: {"can't be blank", _detail}
   ]
 }} =
        Wallets.create(%{ })
```

2022-09-14 23:14 UTC, CristhianRodriguezMolina commented on test/support/wallets/wallet_factory.ex
> +        blockchain_id = Map.get(attrs, :blockchain_id, nil)
@FelipeGuzmanSierra @jhonatan-kmt  Here a better approach would be to insert an account or blockchain in case none is provided.

2022-09-15 13:42 UTC, jhonatan-kmt commented on lib/mintacoin/accounts/wallets.ex
> +    _error -> {:ok, nil}
Hi @CristhianRodriguezMolina, to rescue this case, if we retrieve by id and we pass an invalid UUID, the `Ecto.Query.CastError`  error occurs.
For example: 
with this execution, the error occurs
``` elixir
iex(1)> Mintacoin.Wallets.retrieve_by_id("invalid-uuid")
```

2022-09-15 13:53 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/wallets.ex
> +    _error -> {:ok, nil}
@jhonatan-kmt Ok perfect, thank you.

2022-09-15 14:59 UTC, CristhianRodriguezMolina requested changes

2022-09-15 14:59 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/wallets.ex
> +  end
@jhonatan-kmt In order to avoid this function that can be unpredictable, it is a better approach to manage the query and params in the functions `retrieve_by_id` and `retrieve_by_public_key`, to manage single functionalities. So in further implementations please try to avoid this type of function.

2022-09-15 17:12 UTC, CristhianRodriguezMolina requested changes

2022-09-15 17:12 UTC, CristhianRodriguezMolina commented on test/support/wallets/wallet_factory.ex
> +          blockchain_id: blockchain_id
@jhonatan-kmt The factory allow to directly set an account or a blockchain here:
```suggestion
        account = Map.get(attrs, :account, insert(:account))
        blockchain = Map.get(attrs, :blockchain, insert(:blockchain))
        public_key = Map.get(attrs, :public_key, default_public_key)
        encrypted_secret_key = Map.get(attrs, :encrypted_secret_key, default_encrypted_sk)
        secret_key = Map.get(attrs, :secret_key, default_sk)

        %Wallet{
          id: UUID.generate(),
          public_key: public_key,
          encrypted_secret_key: encrypted_secret_key,
          secret_key: secret_key,
          account: account,
          blockchain: blockchain
```
Please review it and tell me what you think.

2022-09-15 19:03 UTC, jhonatan-kmt commented on test/support/wallets/wallet_factory.ex
> +          blockchain_id: blockchain_id
This approach works, but I think it can be a bit confusing, but, if you want, we cant implement it

2022-09-15 19:15 UTC, CristhianRodriguezMolina commented on test/support/wallets/wallet_factory.ex
> +          blockchain_id: blockchain_id
@jhonatan-kmt I think its a better approach because when we are testing for example we can do this:

```elixir
account = insert(:account)
insert(:wallet, account: account)
```
Instead of this:
```elixir
%{id: account_id} = account = insert(:account)
insert(:wallet, account_id: account_id)
```
It's less tricky to set the whole account in the wallet than only the id, what do you think?

2022-09-15 19:24 UTC, jhonatan-kmt commented on test/support/wallets/wallet_factory.ex
> +          blockchain_id: blockchain_id
@CristhianRodriguezMolina Ok, this looks good to me

2022-09-15 20:09 UTC, CristhianRodriguezMolina approved these changes
Good job :rocket:

2022-09-15 22:14 UTC, merged