Implement the accounts aggregate functions
kommitters/mintacoin pull request #29
Opened 2022-09-19 16:14 UTC by jhonatan-kmt

## Description

Create the aggregate function to create an account and a function `retrieve_by_id` was added in accounts 

Closes #22

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-19 16:54 UTC, miguelnietoa requested changes

2022-09-19 16:54 UTC, miguelnietoa commented on test/mintacoin/accounts/accounts_test.exs
> +      no_existing_uuid: "d9cb83d6-05f5-4557-b5d0-9e1728c42091",
typo: It might be renamed to `non_existing_uuid` or `not_found_uuid`

2022-09-19 19:07 UTC, CristhianRodriguezMolina commented on test/mintacoin/accounts/accounts_test.exs
> +      no_existing_uuid: "d9cb83d6-05f5-4557-b5d0-9e1728c42091",
Ok i agree we'll change it

2022-09-21 13:32 UTC, CristhianRodriguezMolina commented
The implementation of the aggregate function to create the account will be implemented in the PR https://github.com/kommitters/mintacoin/pull/30 together with the implementation of the Oban Worker to process the blockchain transaction.

2022-09-21 13:32 UTC, closed without merging