Implement abstraccion for Encrypter module
kommitters/mintacoin pull request #30
Opened 2022-05-20 22:18 UTC by miguelnietoa

## Description

This PR adds an abstraction for the Encrypter module.

Fixes #15 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-25 14:48 UTC, juanhurtado10 requested changes

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +    :error -> {:error, :decode_64_error}
@miguelnietoa what do you think about using more readable error messages like, `:decoding_error, :encryption_error`?

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +    :eddsa
@miguelnietoa @peterchicaiza please, use a constant.

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +  @spec encode_keypair({public_key :: String.t(), secret_key :: String.t()}) ::
@peterchicaiza @miguelnietoa 

1. a better way to write this spec down.

```elixir
@spec encode_keypair(key_pair :: key_pair()) :: {:ok, key_pair()} 
``` 

2. IMO, this function will never return a `{:error, String.t()}`

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +  def pk_from_sk(secret_key_64) do
@peterchicaiza @miguelnietoa IMO, using acronyms generates confusion.

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +    :eddsa
@miguelnietoa @peterchicaiza Please, use a constant

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/mix.exs
> +      {:swoosh, "~> 1.3"},
@peterchicaiza @miguelnietoa This dependency is not really needed

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/test/mintacoin/encryption_test.exs
> +      "test" = plaintext
@miguelnietoa @peterchicaiza Why not just

```elixir
 {:ok, "test"} = Encryption.decrypt(ciphertext, secret)
```

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/test/mintacoin/encryption_test.exs
> +      {:ok, {assumed_pk, assumed_sk}} = Encryption.pk_from_sk(sk)
@peterchicaiza @miguelnietoa a better assert would be

```elixir
{:ok, {^pk, ^sk}} = Encryption.pk_from_sk(sk)
```

2022-05-25 14:48 UTC, juanhurtado10 commented on apps/mintacoin/test/mintacoin/encryption_test.exs
> +        encoded_token
@peterchicaiza @miguelnietoa use setup to perform this operation instead

2022-05-25 14:52 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/encryption/default.ex
> +    :error -> {:error, :decode_64_error}
Sure!

2022-05-26 19:48 UTC, miguelnietoa commented
Hi there, @juanhurtado10 

We applied the suggested changes.
To facilitate the code review process, we have planned to [remove the Swoosh dependency in another PR](https://github.com/kommitters/mintacoin/issues/32). As well as [separating some functions within the KeyPair module](https://github.com/kommitters/mintacoin/issues/33).

2022-05-26 19:49 UTC, miguelnietoa commented on apps/mintacoin/mix.exs
> +      {:swoosh, "~> 1.3"},
https://github.com/kommitters/mintacoin/issues/32

2022-05-26 20:08 UTC, juanhurtado10 approved these changes
@miguelnietoa @peterchicaiza Awesome job done 👏  🚀

2022-05-26 22:47 UTC, merged