Implement the asset creation with the Stellar SDK
kommitters/mintacoin pull request #44
Opened 2022-09-30 16:19 UTC by FelipeGuzmanSierra

## Description

Implement the creation of an asset using the stellar SDK.

Close #39 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-03 14:26 UTC, CristhianRodriguezMolina requested changes

2022-10-03 14:26 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/crypto/stellar.ex
> +      Keyword.take(opts, [:issuer_secret_key, :distributor_secret_key, :asset_code, :asset_supply])
@jhonatan-kmt Please don't do this because in this way we are forcing the opts to be put in a certain order, so please get the opts one by one.

2022-10-03 14:26 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/crypto/stellar.ex
> +  @type secret_key :: String.t()
@jhonatan-kmt @FelipeGuzmanSierra These types are not being used, please remove them.

2022-10-03 14:26 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/crypto/stellar.ex
> +  @spec format_response({status(), stellar_response()}) :: {:ok, AssetResponse.t()} | error()
@FelipeGuzmanSierra @jhonatan-kmt Please don't forget to add the params name for the types.
```suggestion
  @spec format_response(tx_response :: {status(), stellar_response()}) :: {:ok, AssetResponse.t()} | error()
```

2022-10-04 21:26 UTC, CristhianRodriguezMolina submitted a review, later dismissed
:rocket:

2022-10-04 21:30 UTC, juanhurtado10 commented on lib/mintacoin/accounts/crypto.ex
> +  end
@CristhianRodriguezMolina @jhonatan-kmt @FelipeGuzmanSierra This definitely is not a good approach.

2022-10-04 21:30 UTC, juanhurtado10 requested changes
Some changes are required before merging this PR

2022-10-04 21:34 UTC, CristhianRodriguezMolina commented on lib/mintacoin/accounts/crypto.ex
> +  end
@juanhurtado10 It would be better to create an env variable for each stellar implementation?

2022-10-04 21:34 UTC, juanhurtado10 requested changes

2022-10-04 21:34 UTC, juanhurtado10 commented on lib/mintacoin/assets/crypto.ex
> +    end
@FelipeGuzmanSierra @jhonatan-kmt Instead of doing this, you can link the StellarMock implementation directly into the test run. Something like

```elixir
  setup do
    Application.put_env(:mintacoin, :crypto_impl, StellarMock)

    on_exit(fn ->
      Application.delete_env(:mintacoin, :http_client)
    end)
....
end
´´´

2022-10-04 21:34 UTC, juanhurtado10 commented on lib/mintacoin/assets/crypto/stellar.ex
> +    distributor_secret_key = Keyword.get(opts, :distributor_secret_key)
@FelipeGuzmanSierra @jhonatan-kmt There is a lot of logic involved in this function. This needs to be properly refactored

2022-10-13 20:54 UTC, CristhianRodriguezMolina approved these changes
:rocket: Good job guys

2022-10-13 22:56 UTC, juanhurtado10 approved these changes

2022-10-13 22:59 UTC, merged