Accounts schema and boundaries
kommitters/mintacoin pull request #47
Opened 2022-06-01 19:24 UTC by peterchicaiza

## Description

Thi PR creates the Accounts' schema and boundaries based on the accounts as the entity representing a user in the system. 

### Accounts Functions
- `create/1`
- `retrieve/1`
- `update/1`
- `delete/1`
- `recover_secret_key/2`

ℹ️ This PR closes #26

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-01 20:04 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/accounts/schema.ex
> +  alias Ecto.Changeset
```suggestion
  alias Ecto.Changeset
  alias Mintacoin.{Encryption, Mnemonic}
```

2022-06-02 22:50 UTC, miguelnietoa commented
Tests implemented!

2022-06-02 23:36 UTC, juanhurtado10 requested changes

2022-06-02 23:36 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/accounts/accounts.ex
> +  def retrieve(_address), do: {:error, :bad_argument}
@peterchicaiza @miguelnietoa IMO, `:not_found` has a better context as a response

2022-06-02 23:36 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/accounts/accounts.ex
> +    update(address, %{status: @archived_status})
@peterchicaiza @miguelnietoa a deletion date `archive_at | deleted_at` would be required as well. 

**Note:** This is not something urgent. You can address it in a different issue, is up to you!

2022-06-02 23:36 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/accounts/accounts.ex
> +    with {:ok, %{encrypted_signature: encrypted_signature}} <- retrieve(address),
@peterchicaiza @miguelnietoa Why are you using a map instead of the `Account` struct?

2022-06-02 23:36 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/accounts/schema.ex
> +    |> (&put_change(changeset, :address, &1)).()
@peterchicaiza @miguelnietoa Avoid using a pipe operator when there is just one process step.

```elixir
    put_change(changeset, :address, UUID.generate())
```

2022-06-02 23:36 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/minters/schema.ex
@peterchicaiza @miguelnietoa The Minters implementation should have its own PR, shouldn't it?

2022-06-03 15:35 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/accounts/accounts.ex
> +    update(address, %{status: @archived_status})
Issue https://github.com/kommitters/mintacoin/issues/50

2022-06-03 16:17 UTC, juanhurtado10 approved these changes

2022-06-03 16:18 UTC, merged