README documentation update
kommitters/mintacoin pull request #52
Opened 2022-10-07 14:39 UTC by CristhianRodriguezMolina

## Description

Fixes #51

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-07 19:29 UTC, miguelnietoa requested changes
@CristhianRodriguezMolina good documentation! I've added some comments, let me know what you think 💯

2022-10-07 19:29 UTC, miguelnietoa commented on README.md
> +The `Create account` endpoint allows us to create accounts, this endpoint returns us the necessary to manage our account in Mintacoin, the address (Mintacoin public key), the signature (Mintacoin sec
```suggestion
It creates an account on Mintacoin and the given blockchain.
This endpoint returns the necessary to manage an account in Mintacoin: **address** (Mintacoin public key), **signature** (Mintacoin secret key), and **seed words** (to recover the signature).
```

2022-10-07 19:29 UTC, miguelnietoa commented on README.md
> +
@CristhianRodriguezMolina I consider `signature`, `address` and `seed_words` with code format and in a more direct description could look better. What do you think?
```suggestion
Recovers the `signature` with the `address` and the `seed_words` of an account.
```

2022-10-07 19:29 UTC, miguelnietoa commented on README.md
> +##### Curl request
@CristhianRodriguezMolina Taking a good look at it... I think we could remove "HTTP request" and change "Curl request" with "Example request" 🤔

2022-10-07 20:34 UTC, CristhianRodriguezMolina commented on README.md
> +| `status`  | Integer | Status of the request.                                            |
You're right we can specify that it is an HTTP status code

2022-10-07 20:35 UTC, CristhianRodriguezMolina commented on README.md
> +```
I'll add a section for the body params of each endpoint.

2022-10-07 20:42 UTC, CristhianRodriguezMolina commented on README.md
> +##### Curl request
What do you think about something like this: 

![image](https://user-images.githubusercontent.com/50219561/194649365-f8424564-3dcb-41cd-8338-3e442265f7a6.png)

It would look like this:

![image](https://user-images.githubusercontent.com/50219561/194649411-2bafe796-aac4-41c4-98bc-61887c42aa38.png)

2022-10-07 20:51 UTC, juanhurtado10 commented on README.md
> +##### Curl request
@CristhianRodriguezMolina @miguelnietoa why not use Gitbook to place this type of documentation?

2022-10-07 20:57 UTC, juanhurtado10 requested changes

2022-10-07 20:57 UTC, juanhurtado10 commented on README.md
> +##### Curl request
my 5 cents: 
1. Point `docs.mintacoin.co` to Gitbook.
2. Synchronize the Gitbook space with the GitHub repo.
3. Write the documentation in .md which automatically syncs the Gitbook space.

2022-10-11 21:39 UTC, miguelnietoa approved these changes

2022-10-11 21:47 UTC, juanhurtado10 approved these changes

2022-10-11 22:14 UTC, merged