Expose accounts endpoints
kommitters/mintacoin pull request #54
Opened 2022-06-06 23:20 UTC by miguelnietoa

## Description
This PR exposes the CRUD actions for `accounts` together with the recover endpoint.

Fixes #27 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-07 15:54 UTC, juanhurtado10 requested changes

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +  @allowed_params ["email", "name"]
@miguelnietoa please, use a sigil instead

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +  @spec create(conn :: conn(), params :: params()) :: {:error, error()} | conn()
@miguelnietoa
```elixir
.
.
@spec create(conn :: conn(), params :: params()) :: conn() | {:error, error()}
```

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +      {:ok, _account} -> send_resp(conn, :no_content, "")
@miguelnietoa why return an empty body response?

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +      _error -> {:error, :bad_request}
@miguelnietoa this seems to be a typical pattern across actions. Maybe using a common function with pattern matching may simplify, what do you think?

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +      |> String.to_existing_atom()
@miguelnietoa Atoms are not garbage collected. Think about what will happen with the system memory if someone performs a request including a large set of params and you try to convert all of them into atoms?

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/views/accounts_view.ex
> +  @type object :: map()
@miguelnietoa IMO, we should avoid using words that represent the OOP paradigm like `object`. What about we use `resource` instead?

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/views/accounts_view.ex
> +  @public_attributes [:address, :email, :name, :derived_key, :seed_words, :signature, :status]
@miguelnietoa please, use a sigil instead

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/test/mintacoin_web/controllers/accounts_controller_test.exs
> +  @auth_header "authorization"
@miguelnietoa Why are you using constants for the test assertions? IMO, it is not a good approach, the setup macro should be used instead

2022-06-07 15:54 UTC, juanhurtado10 commented on apps/mintacoin_web/lib/mintacoin_web/controllers/accounts_controller.ex
> +  defp fetch_allowed_params(params) do
@miguelnietoa this seems something that can be removed from the controller's logic. What about using a standalone module for these params transformations?

2022-06-08 15:01 UTC, miguelnietoa commented
Requested changes applied! We look forward to the new code review. 😄

2022-06-08 17:11 UTC, merged