Add OSPO docs and related policies
kommitters/mintacoin pull request #6
Opened 2022-09-08 20:37 UTC by CristhianRodriguezMolina

## Description

Fixes #3 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-08 21:08 UTC, miguelnietoa requested changes

2022-09-08 21:08 UTC, miguelnietoa commented on CONTRIBUTING.md
> +If you see any issues that are assigned to a particular person or have the `work in progress` label, that means
Let's write the same labels as are defined in the OSPO by replacing `work in progress` with `📍 Work in progress`!

2022-09-08 21:39 UTC, CristhianRodriguezMolina commented on CONTRIBUTING.md
> +If you see any issues that are assigned to a particular person or have the `work in progress` label, that means
It looks good to me

2022-09-09 15:17 UTC, miguelnietoa approved these changes

2022-09-09 15:23 UTC, merged