Create Assets boundaries and tests
kommitters/mintacoin pull request #64
Opened 2022-06-10 20:32 UTC by miguelnietoa

## Description

Fixes #60

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-10 21:06 UTC, juanhurtado10 requested changes

2022-06-10 21:06 UTC, juanhurtado10 commented on apps/mintacoin/test/mintacoin/assets/assets_test.exs
> +        code: "ASSET_CODE",
@miguelnietoa the system should be capable to create multiple assets with the same asset code.

For instance, two minters should be allowed to create an asset with the same asset code.

My suggestion, in this case, is to provide a "public address" to the assets something like `MTK:SHORT-UNIQUE-ID`

What do you think?

2022-06-10 23:19 UTC, peterchicaiza commented on apps/mintacoin/test/mintacoin/assets/assets_test.exs
> +        code: "ASSET_CODE",
The asset's code is composed of the `code` given as a parameter and the minter's `address`. Later we can think about improving the format of the minters' address to make it more user-friendly.

2022-06-13 16:04 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/utils/default_resources.ex
> +defmodule Mintacoin.Utils.DefaultResources do
Yes, we have decided to implement an abstraction for blockchain networks, using Stellar by default.

2022-06-13 16:09 UTC, peterchicaiza approved these changes

2022-06-13 16:15 UTC, merged