Update readme documentation
kommitters/mintacoin pull request #68
Opened 2022-10-13 16:03 UTC by SanGeeky

## Description
Closes #67 

This PR updates the project Readme with the following documentation changes:
- Update project description.
- Describes project roadmap.
- Update the project setup with their config file.

## Type of change
- [x] This change requires a documentation update

## Checklist
- [x] I have made corresponding changes to the documentation

2022-10-17 20:25 UTC, miguelnietoa requested changes
@SanGeeky Comments added!

@CristhianRodriguezMolina could you please help me with the review of the setup instructions?

2022-10-17 21:24 UTC, CristhianRodriguezMolina commented on README.md
> +    - **`"BLOCKCHAINS_NETWORK"`** with `"testnet"`.
This is used to get the blockchains matching with the `network` field of the blockchain table, this field is an `:atom` so we can set this here as an atom.

2022-10-17 21:27 UTC, CristhianRodriguezMolina commented on README.md
> +    - **`"BLOCKCHAINS_NETWORK"`** with `"testnet"`.
This is related to the `network` field of the blockchain table which is an atom, so we can set this as an atom, what do you think @SanGeeky?

2022-10-17 22:08 UTC, SanGeeky commented on README.md
> +    - **`"BLOCKCHAINS_NETWORK"`** with `"testnet"`.
After reviewing for the development process we will define this variable as atom.

2022-10-17 22:54 UTC, juanhurtado10 requested changes
@SanGeeky looks really good! Just one minor improvement ... It is important to clarify the blockchain network we're using for the API.

2022-10-18 14:34 UTC, CristhianRodriguezMolina submitted a review, later dismissed

2022-10-18 15:29 UTC, merged