#67 Create Wallet schema
kommitters/mintacoin pull request #71
Opened 2022-06-15 00:56 UTC by MrJuanGaviriaK

## Description
Closes #67 

Create the Wallet schema and migration:
id: uuid
blockchain_id: uuid
account_id: uuid
address: string
encrypted_secret: string
timestamps()

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2022-06-15 13:42 UTC, miguelnietoa requested changes
Pretty good, some comments were added @MrJuanGaviriaK !

2022-06-15 13:42 UTC, miguelnietoa commented on apps/mintacoin/priv/repo/migrations/20220614134510_add_wallets_table.exs
> +      add(:secret, :string, null: false)
For security reasons, we will not store the secret itself but an encrypted secret, therefore I think it would be better to rename the field to `encrypted_secret`.

2022-06-15 13:42 UTC, miguelnietoa commented on apps/mintacoin/priv/repo/migrations/20220614134510_add_wallets_table.exs
> +  end
By definition and simplicity, an Account can have only one wallet per blockchain. So we can create a unique index to guarantee this, what do you think?

2022-06-15 16:06 UTC, MrJuanGaviriaK commented on apps/mintacoin/priv/repo/migrations/20220614134510_add_wallets_table.exs
> +  end
Yes thanks, I'm going to fix it!!!

2022-06-15 23:27 UTC, MrJuanGaviriaK commented
@miguelnietoa  done, thanks!!!

2022-06-16 13:40 UTC, miguelnietoa requested changes
I believe that by applying the suggested changes, this PR would be ready to merge! 🔥

2022-06-16 13:40 UTC, miguelnietoa commented on apps/mintacoin/priv/repo/migrations/20220614134510_add_wallets_table.exs
> +    create unique_index(:wallets, [:account_id, :blockchain_id])
Yes, this constraint is really necessary! Additionally, we could define a name such as `account_blockchain_index`.
```suggestion
    create unique_index(:wallets, [:account_id, :blockchain_id], name: :account_blockchain_index)
```

2022-06-16 13:40 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/wallets/schema.ex
>    end
It is important to validate the unique constraint from the changeset by adding this:
```suggestion
    |> foreign_key_constraint(:account_id)
    |> foreign_key_constraint(:blockchain_id)
    |> unique_constraint([:account_id, :blockchain_id], name: :account_blockchain_index)
  end
```

2022-06-16 15:36 UTC, MrJuanGaviriaK commented on apps/mintacoin/lib/mintacoin/wallets/schema.ex
>    end
Thanks!!!

2022-06-16 23:25 UTC, MrJuanGaviriaK commented
@miguelnietoa done! Thanks.

2022-06-16 23:30 UTC, miguelnietoa approved these changes
Thanks for your contribution @MrJuanGaviriaK 🚀

2022-06-16 23:37 UTC, miguelnietoa commented
Just a nit, please check the [commit signatures](https://docs.github.com/en/enterprise-server@3.0/authentication/managing-commit-signature-verification/about-commit-signature-verification), verified commits are needed as rule for merging PRs. 😅

2022-06-17 12:05 UTC, merged