Implement the create asset worker
kommitters/mintacoin pull request #71
Opened 2022-10-14 15:48 UTC by jhonatan-kmt

## Description

Create the worker that will perform the transactions to create assets into the blockchains.

Closes #46 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-17 20:25 UTC, CristhianRodriguezMolina requested changes

2022-10-17 20:25 UTC, CristhianRodriguezMolina commented on test/mintacoin/accounts/balances_test.exs
> +        Balances.increase_balance(balance_id, "20")
@jhonatan-kmt Here you can set a decimal with several decimals in order to test a more realistic case.

2022-10-18 14:58 UTC, CristhianRodriguezMolina requested changes

2022-10-18 14:58 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/assets.ex
> +      {:ok, encrypted_secret_key} = Cipher.encrypt_with_system_key(secret_key)
@jhonatan-kmt This is a bad use of the `with` statement, these two function calls should be in the `with`.

2022-10-18 14:58 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/workers/create_asset.ex
> +    float_supply = supply |> Decimal.new() |> Decimal.to_float()
@jhonatan-kmt Please remove these gaps.

2022-10-18 22:10 UTC, CristhianRodriguezMolina requested changes

2022-10-18 22:10 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/assets.ex
> +        ) :: {:ok, encrypted_key} | {:error, error()}
@jhonatan-kmt The `encrypted_key` has the `()` missing.

2022-10-18 22:40 UTC, CristhianRodriguezMolina requested changes

2022-10-18 22:40 UTC, CristhianRodriguezMolina commented on lib/mintacoin/assets/assets.ex
> +           Wallets.retrieve_by_account_id_and_blockchain_id(account_id, blockchain_id),
@jhonatan-kmt I think that you can receive here the wallet instead of the account, in order to avoid validating if the wallet exists in the blockchain. The wallet already has the `account_id` so you can "kill two birds with one stone".

2022-10-18 22:50 UTC, jhonatan-kmt commented on lib/mintacoin/assets/assets.ex
> +           Wallets.retrieve_by_account_id_and_blockchain_id(account_id, blockchain_id),
Good advice, thanks!!

2022-10-19 20:40 UTC, CristhianRodriguezMolina approved these changes

2022-10-19 20:44 UTC, merged