Use bearer token as an authentication mechanism #73
kommitters/mintacoin pull request #77
Opened 2022-10-18 16:48 UTC by samu975

## Description

This PR changed the get_token function in order to receive bearer token.

-     Changed function get_token.
-     Uptdated account_controller_test.exs

Fixes #73 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-18 21:02 UTC, CristhianRodriguezMolina requested changes
@samu975 Please ensure to get the feature branch from the branch you are gonna merge with, to ensure that the files and commits in the feature branch are up to date, for example, in this case, you have to get the feature branch like so:

```bash
> git checkout v0.3
> git checkout -b 73-feature-branch
```

2022-10-18 23:41 UTC, SanGeeky approved these changes

2022-10-18 23:41 UTC, SanGeeky commented on lib/mintacoin_web/plugs/verify_api_token.ex
> +    case get_req_header(conn, "authorization") do
@samu975  please update this key with `Authorization` which is the standard for the authorization token.

2022-10-19 15:29 UTC, samu975 commented on lib/mintacoin_web/plugs/verify_api_token.ex
> +    case get_req_header(conn, "authorization") do
Hi David, Authorization is the standard for the authorization token, but in this case, elixir only accepts header keys in lowercase, so if I change "authorization" to "Authorization," a Plug.Conn.InvalidHeaderError will appear

2022-10-19 19:10 UTC, SanGeeky requested changes
@samu975 after reviewing this PR I think we should use the word "authorization" instead of "authentication" for the other private functions and the error messages, to maintain code consistency. Do not forget to update the test also, thanks in advance.

2022-10-19 21:52 UTC, SanGeeky approved these changes

2022-10-19 22:15 UTC, CristhianRodriguezMolina approved these changes

2022-10-20 14:54 UTC, SanGeeky approved these changes

2022-10-20 15:08 UTC, merged