Implement the create asset trustline worker
kommitters/mintacoin pull request #79
Opened 2022-10-19 21:12 UTC by jhonatan-kmt

## Description

Create the worker that will perform the transactions to create an asset trustline into the blockchains.

Closes #47

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-20 17:55 UTC, SanGeeky requested changes

2022-10-21 17:52 UTC, SanGeeky requested changes

2022-10-21 17:52 UTC, SanGeeky commented on lib/mintacoin/accounts/accounts.ex
> +    end
@jhonatan-kmt let's rewrite this function, i suggest the following change:
```suggestion
    case system_encrypt_secret_key(trustor_wallet, signature) do
      {:ok, encrypted_secret_key} ->
        trustor_wallet_id
        |> AssetHolders.retrieve_by_wallet_id_and_asset_id(asset_id)
        |> process_trustor(asset_id, trustor_wallet)
        |> dispatch_create_trustline_job(encrypted_secret_key, code)
      {:error, error} -> {:error, error}
    end
```

This implementation completes 100% of the test coverage of the module.

2022-10-21 19:51 UTC, jhonatan-kmt commented on lib/mintacoin/accounts/accounts.ex
> +    end
I like it, I will implement it. Thanks for the suggestion

2022-10-21 20:24 UTC, SanGeeky approved these changes
You rock !!! :guitar:

2022-10-21 20:36 UTC, merged