dockerizing project for dev and test mode
kommitters/mintacoin pull request #81
Opened 2022-10-20 02:57 UTC by keliumJU

## Description

motivation: CRC dependency compilation error occurred on windows 11 and possibly some recent mac os operating systems, however this error does not occur on linux systems.

For this reason, I started the process of dockerizing the developer mode of the project, adding a new file Dockerfile.dev and along with the default container orchestrator, which is docker-compose.

a container was created for the database and the application in phoenix, the dev.exs.example file was modified so that Mintacon.Repo connects to the postgres container, the same in test.exs, the setup process with docker would remain as follows:

1. Mintacoin requires a development configuration file. Copy the example with the following command:

`cp config/dev.exs.example config/dev.exs`

and change the database connection settings to Docker mode dev

2. Within the file dev.exs replace the following variables

`STELLAR_FUND_SECRET_KEY` with the secret key created from the Stellar Laboratory.
`BLOCKCHAINS_NETWORK` with `testnet`
`API_TOKEN` with `any_api_token_value`

3. to build the phoenix and postgres image:
`docker-compose build
`
4. to upload the migrations to the postgres container:
`docker-compose run mix ecto.setup`

5. to launch the application:
`docker-compose up`

**Now you can visit [localhost:4000](http://localhost:4000/) from your browser.**

### to test
1. in config/test.exs you must uncomment the -docker mode dev- which is the configuration for the connection to the database

2. If you want to test the tests, you must do it from the CLI of the phoenix container, changing the dev mode to test
$ `MIX_ENV=test`
$ `mix test`

any changes to lib/ files are hot reloaded which is reflected on the host.

note: the first compilation of both the phoenix container and the tests is quite slow, approximately 15 min each, but I would like to know how long each one takes on your computers since mine is quite slow, finally step 1, 5 and 6 of setup without docker, were automated.

Fixes # 53

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-21 14:34 UTC, SanGeeky commented
Hello @keliumJU, I was testing your solution, but it was not possible to make a successful request, and I was not able to run the test environment. Related to the build time it does not take too much time tbh.

I was researching more about dockerize the project using a single `Dockerfile` and I found the usage of [multi-stage builds](https://docs.docker.com/build/building/multi-stage/), could be useful to reuse the existing `Dockerfile` in the project. Also can be useful [this documentation](https://docs.docker.com/compose/environment-variables/) about environment variables within Docker. 

Finally, remember as an open-source project we need to keep all very simple, feel free to ask any doubts.

PD, Please use the PR template for your description and mention the related issue, which in this case is issue 53.

2022-10-22 01:09 UTC, keliumJU commented
@SanGeeky I have used some multi-stage builds to leave a single "Dockerfile", as well as adding some environment variables to my docker-compose. I know it's not the best approach, possibly it's better to use an entrypoint and reuse code from the dev to prod stage, but I'd like to know what you think of the current state, also when you try the setup again it would be better to follow the guide in the file " Readme.md", since the one in the commit was wrong.

2022-10-25 23:47 UTC, SanGeeky requested changes
@keliumJU In general I see a very clean implementation, we just need to simplify the setup process, to build and run the docker container.

2022-10-25 23:47 UTC, SanGeeky commented on docker-compose.yml
> +      - 'pgdata:/var/lib/postgresql/data'
@keliumJU let's reorder this like this:
```suggestion
  mintacoin_db:
    image: postgres:14-alpine
    container_name: mintacoin_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mintacoin_dev
    networks:
      - mintacoin
```

2022-10-25 23:47 UTC, SanGeeky commented on docker-compose.yml
> +      - .:/app
@keliumJU  I suggest these changes and organization:
```suggestion
    mintacoin_api:
        container_name: mintacoin_api
        build:
          context: .
          target: dev
        volumes:
          - .:/app
        ports:
          - 4000:4000
        environment:
          - CONTAINER_HOST=mintacoin_api
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB_LOCAL=mintacoin_dev
          - POSTGRES_DB_TEST=mintacoin_test
          - POSTGRES_PORT=5432
          - POSTGRES_HOST=mintacoin_db
        depends_on:
          - mintacoin_db
        networks:
          - mintacoin
```

2022-10-25 23:47 UTC, SanGeeky commented on docker-compose.yml
> +  pgdata:
@keliumJU I think this is not necessary, instead place the network settings:
```
networks:
  mintacoin:
    driver: bridge
    name: mintacoin
```

2022-10-25 23:47 UTC, SanGeeky commented on lib/mintacoin_web/controllers/accounts_controller.ex
> +
@keliumJU please remove this.

2022-10-25 23:47 UTC, SanGeeky commented on config/dev.exs.example
> +
@keliumJU why not just use the current implementation and define system variables and default values:

```
  database: System.get_env("POSTGRES_DB_LOCAL", "mintacoin_dev"),
  username: System.get_env("POSTGRES_USER", "postgres"),
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  ```
  
  Also please update the `http` option, from `MintacoinWeb.Endpoint`:
  `http: [port: 4000],`
  
  This works for me to be able to access the service

2022-10-26 15:07 UTC, keliumJU commented on .env
> +TAG_COMPOSE=3.6
ok, then I remove the .env file and the connection to the database is done through the current implementation

2022-10-26 15:31 UTC, SanGeeky commented on .env
> +TAG_COMPOSE=3.6
You are right, as I suggested in these comments:
 1. [Mintacoin API comment.](https://github.com/kommitters/mintacoin/pull/81#discussion_r1005061816)
 2. [Configuration file comment.](https://github.com/kommitters/mintacoin/pull/81#discussion_r1005065054)

2022-10-26 20:44 UTC, keliumJU commented on Dockerfile
> +apt-get install -y postgresql-client
Although, it works well, some dependency may be missing in the future, so I will add it.

2022-10-26 20:47 UTC, keliumJU commented on Dockerfile
> +
The truth is that I did not find any reference to help me answer this question, however I do not think it is necessary to add it because the container is well built, also probably the context of the docker-compose is responsible for adding the root of the project, but I'm not sure.

2022-10-26 20:47 UTC, keliumJU commented on Dockerfile
> +ENV MIX_ENV="dev"
ok, I'll remove it

2022-10-26 21:21 UTC, keliumJU commented on Dockerfile
> +CMD mix deps.get && mix phx.server
ready, it takes care of making the setup shorter, with this line it avoids "docker-compose run web ecto.setup"

2022-10-26 21:22 UTC, keliumJU commented on docker-compose.yml
> +version: '${TAG_COMPOSE}'
okay, without .env we leave the fixed versions

2022-10-26 22:17 UTC, keliumJU commented on docker-compose.yml
> +  pgdata:
I had not used the network before, apparently they are useful to communicate or separate containers. i have changed it

2022-10-26 22:17 UTC, keliumJU commented on lib/mintacoin_web/controllers/accounts_controller.ex
> +
of course, it was just for testing, I will avoid placing test code.

2022-10-26 22:38 UTC, keliumJU commented on docker-compose.yml
> +  pgdata:
I tried to remove the `volume:` but when I did the docker-compose build it generated a reference error, since it is defined in the volumes of the mintacoin_db service, also I had to add the PGDATA to the enviroment.

2022-10-26 22:40 UTC, keliumJU commented on docker-compose.yml
> +      - 'pgdata:/var/lib/postgresql/data'
ok, change made

2022-10-26 22:41 UTC, keliumJU commented on docker-compose.yml
> +      - .:/app
ok, change made and I like this

2022-10-26 22:41 UTC, keliumJU commented on config/dev.exs.example
> +
I have tried it with all the changes you recommended and it looks and works quite well, thanks.

2022-10-26 23:45 UTC, keliumJU commented on Dockerfile
> +CMD mix deps.get && mix phx.server
And with respect to the seed, I try to solve it with a Repo.exists?/2 and a query

2022-10-28 15:06 UTC, SanGeeky commented on Dockerfile
> +
You are right it is not necessary to add it, thank you for the clarification.

2022-10-28 20:24 UTC, SanGeeky requested changes
@keliumJU Excellent improvement, this a very clean solution, I just add minor changes, and please ensure to remove the blank spaces in the files (you may able to make this automatically by setting up your editor).

2022-10-28 20:24 UTC, SanGeeky commented on README.md
> +
@keliumJU update this documentation like this:

```markdown
#### Setting up with Docker

1. First, you need to execute the steps **2** and **3** from previous setup.

2. Build the Phoenix and Postgres images with `docker-compose build`.

3. Finally, run the containers with `docker-compose up`.

Now you can visit [`localhost:4000`](http://localhost:4000) from your browser(only if ports 4000 and 5432 were available on your computer).

#### Testing with Docker

Run the tests with `docker-compose run mintacoin_api mix test`.

#### Run commands with Docker

* Run the IEx console with `docker-compose run mintacoin_api iex -S mix`.
* Run your new migrations with `docker-compose run mintacoin_api mix ecto.migrate`. 
* Install new dependencies with `docker-compose run mintacoin_api mix deps.get`.
* Run any mix task with `docker-compose run mintacoin_api mix <task>`.
```
BTW update the headings the following subtitles:

```markdown
### Requirements
#### Setting up
#### Testing
```

2022-10-31 15:10 UTC, keliumJU commented on README.md
> +
sure, updated documentation.

2022-10-31 15:11 UTC, keliumJU commented on config/dev.exs.example
>  #
sorry, I had made the change in dev.exs not in dev.exs.example. now it is updated.

2022-10-31 15:12 UTC, keliumJU commented on config/test.exs
> +  database: System.get_env("POSTGRES_DB_LOCAL", "mintacoin_test#{System.get_env("MIX_TEST_PARTITION")}"),
I hadn't noticed, now it's updated

2022-10-31 15:22 UTC, SanGeeky commented on priv/repo/seeds.exs
> +end
@keliumJU Oh you are right, is because this file is a script, not a module, so keep this file as script to skip the spec error.

2022-10-31 16:45 UTC, keliumJU commented
I have taken notes from your last comment: sign the commits, don't force the push and keep the commit history, normally when I do the rebase -i, I usually delete the commit history leaving only the first one. thanks.

2022-10-31 20:05 UTC, SanGeeky requested changes

2022-10-31 20:05 UTC, SanGeeky commented on README.md
> +Now you can visit [`localhost:4000`](http://localhost:4000) from your browser(only if port 4000 is available).
@keliumJU add a single space between "browser" and the parentheses

2022-10-31 20:05 UTC, SanGeeky commented on config/dev.exs.example
> +
@keliumJU remember to remove the blank spaces.

2022-10-31 20:05 UTC, SanGeeky commented on priv/repo/seeds.exs
> +defmodule Seeds.Actions do
@keliumJU same from this [comment](https://github.com/kommitters/mintacoin/pull/81#discussion_r1009548326).

2022-10-31 20:05 UTC, SanGeeky commented on priv/repo/seeds.exs
> +  def check_if_blockchain_exists() do
@keliumJU for future implementations, remember to place first the public functions and then the private functions.

2022-11-01 23:25 UTC, keliumJU commented on README.md
> +1. First, you must do steps **2** and **3** of the previous setup.
ok, corrected.

2022-11-01 23:25 UTC, keliumJU commented on README.md
> +Now you can visit [`localhost:4000`](http://localhost:4000) from your browser(only if port 4000 is available).
ok, corrected.

2022-11-01 23:27 UTC, keliumJU commented on config/dev.exs.example
> +
I will try to remember it, I almost always fail at the same thing.

2022-11-01 23:30 UTC, keliumJU commented on priv/repo/seeds.exs
> +  def check_if_blockchain_exists() do
I will keep it in mind

2022-11-01 23:30 UTC, keliumJU commented on priv/repo/seeds.exs
> +defmodule Seeds.Actions do
ok, revised

2022-11-02 00:05 UTC, keliumJU commented
@SanGeeky I encountered many inconveniences when I did not force the push, I will have to do more research on the subject.

2022-11-02 00:36 UTC, SanGeeky commented on config/dev.exs.example
> +
You can set up your editor to remove the blank spaces automatically.

2022-11-02 00:38 UTC, SanGeeky commented on priv/repo/seeds.exs
> +  end
I really like this, excellent!

2022-11-02 00:38 UTC, SanGeeky submitted a review, later dismissed

2022-11-02 22:44 UTC, SanGeeky approved these changes

2022-11-02 22:55 UTC, merged