Code refactoring in stellar.ex
kommitters/mintacoin pull request #83
Opened 2022-10-20 20:22 UTC by Odraxs

## Description

Improving stellar implementation code, so will be easier modifications or maintainability

Fixes #64 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-20 22:37 UTC, SanGeeky requested changes
@Odraxs I just added the following comments in order to follow the code style we use in the project. Please do not forget to add the test if required.

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    fund_info = fund_information()
@Odraxs Please use pattern matching with the result obtained from this function.

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  defp fund_information do
@Odraxs Let's rename this function like this:
```suggestion
  defp funder_account_information do
```

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    {pk, _fund_private_key} = fund_keypair = fund_key_pair_from_system()
@Odraxs You can move the content from `fund_key_pair_from_system/0` here.

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +      |> TxBuild.Signature.new()
@Odraxs Use a single line for this operation

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
>      {public_key, secret_key} = KeyPair.random()
@Odraxs Move this line to the top of the function.

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +      |> TxBuild.SequenceNumber.new()
@Odraxs this will not work, because the function `Horizon.Accounts.fetch_next_sequence_number()/1` will return a response with one of the following results `{:ok, resource()} | {:error, Error.t()}`. 

In addition to this please move all of these operations to a single private function called `get_sequence_number/1`

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    |> TxBuild.new(sequence_number: sequence_number)
@Odraxs You can group this part into the pipes, for example
```suggestion
    fund_public_key
    |> TxBuild.Account.new()
    |> TxBuild.new(sequence_number: sequence_number)
```

2022-10-20 22:37 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    |> execute_transaction(public_key, secret_key)
@Odraxs as the issue mentions:

> Keep in mind to chain all the previous functions using the pipe operator.

You can move all the functions and create a single statement with the pipe operator, and this will remove all the variable assignments.

2022-10-20 22:39 UTC, SanGeeky requested changes

2022-10-20 22:39 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    %{fund_public_key: pk, fund_signature: signature}
Similar to the comment [described here ](https://github.com/kommitters/mintacoin/pull/83#discussion_r1001168230) rename resulting map with:

- `funder_public_key`
- `funder_signature`

2022-10-21 14:45 UTC, SanGeeky requested changes
@Odraxs excellent improvement! Just one more change, add the `@spec` to the functions created

2022-10-21 15:47 UTC, Odraxs commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    {pk, _fund_private_key} = fund_keypair = fund_key_pair_from_system()
I don't have very clear this comment, I understood to call `fund_key_pair_from_system/0` on `create_account` and only pass the public key as a parameter or I'm wrong ?

2022-10-21 16:20 UTC, Odraxs commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    {pk, _fund_private_key} = fund_keypair = fund_key_pair_from_system()
Nvm, I catch it now

2022-10-21 16:29 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    {pk, _fund_private_key} = fund_keypair = fund_key_pair_from_system()
@Odraxs sorry, let's keep the current changes, just rename the function as `funder_key_pair_from_system/0`. Do not forget to be consistent with the variable names.

2022-10-21 16:29 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    {pk, _fund_private_key} = fund_keypair = fund_key_pair_from_system()
@Odraxs sorry, let's keep the current changes, just rename the function as `funder_key_pair_from_system/0`. Do not forget to be consistent with the variable names.

2022-10-21 19:16 UTC, SanGeeky requested changes
@Odraxs seems fine, but we can improve the type specs and how they are defined, please review the following file `lib/mintacoin/assets/crypto/stellar.ex` to keep the code very clean.

Check out the [user-defined types documentation](https://hexdocs.pm/elixir/1.13/typespecs.html#user-defined-types) for more information.

2022-10-21 19:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +        }
@Odraxs refactor this spec in a `@type` called `funder_account_information` with `map()` type.

2022-10-21 19:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @type sequence_number :: TxBuild.SequenceNumber.t()
@Odraxs please organize these types in ascendant alphabetic order.

2022-10-21 19:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @spec funder_key_pair_from_system() :: {public_key(), secret_key()}
@Odraxs refactor this spec in a `@type` called `key_pair`.

2022-10-21 19:51 UTC, Odraxs commented on lib/mintacoin/accounts/crypto/stellar.ex
> +        }
@SanGeeky If i call the type as `funder_account_information` it refers to the function 

![image](https://user-images.githubusercontent.com/62166813/197277132-bb7af634-0985-4a08-b57c-99027beea15b.png)

Is ok like that ? or  can I rename it as `funder_account_info` ?

2022-10-21 20:14 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +        }
Yep, is fine, we are just typing the data returned. Keep in mind is better to be consistent with the names, and prefer descriptive names instead of abbreviations.

2022-10-21 22:16 UTC, SanGeeky requested changes

2022-10-21 22:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @type account :: TxBuild.CreateAccount.t()
@Odraxs you can use an alias for this type and other similar implementations:

```suggestion
   alias Stellar.TxBuild.{CreateAccount}

  @type account :: CreateAccount.t()
```

Checkout this [documentation about multiple alias](https://elixir-lang.org/getting-started/alias-require-and-import.html#multi-aliasimportrequireuse).

2022-10-21 22:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @spec funder_key_pair_from_system() :: kew_pair()
@Odraxs rename as `key_pair()`

2022-10-21 22:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +          {:error, :sequence_number} | sequence_number()
@Odraxs here just use for the returning type `sequence_number()`

2022-10-21 22:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +    sequence_number = get_sequence_number(funder_public_key)
@Odraxs, please define a type for the result of this function called `tx_envelop`

2022-10-21 22:16 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  defp execute_transaction(envelope, public_key, secret_key) do
@Odraxs please rename the `envelope` parameter as `tx_envelope`, also describe it in the spec.

2022-10-21 22:19 UTC, SanGeeky reviewed
@Odraxs take into account the recommendation of [this comment.](https://github.com/kommitters/mintacoin/pull/83#pullrequestreview-1151421578)

2022-10-24 16:38 UTC, SanGeeky requested changes
@Odraxs FYI the tests for this module are being mocked, therefore is necessary to test the results using the implemented endpoints and review the operations of your master account in the Stellar Expert, to watch easiest the transactions created. I drop an [example of my master account](https://stellar.expert/explorer/testnet/account/GBF2MB6MFY52Z7OPKHFBIOBE5JOUOZH4NI6AWVC3CRPTGETT3Q7BNK63).

Please review our [documentation to create an account](https://docs.mintacoin.co/#create-account), and I left with you an example using cURL in my local instance:

```bash
curl -X POST -H \
    -H  'authorization: yourapitoken' \
    -H 'Content-Type: application/json' \
    -d '{"blockchain": "stellar"}' \
    "http://localhost:4000/accounts"
```
In case of any error review the table `oban_jobs` within your DB, and the field `errors`.

2022-10-24 16:38 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  }
@Odraxs separate this in another alias like this:
```suggestion
  alias Stellar.TxBuild.{CreateAccount, SequenceNumber, Signature}
```

2022-10-24 16:38 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @type tx_envelope :: binary()
@Odraxs update this in this way
```suggestion
    @type tx_envelope :: {:ok, envelope()} | {:error, atom()}
```

and the `envelop()` type should be `String.t()`

2022-10-24 16:38 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  defp execute_transaction(envelope, public_key, secret_key) do
@Odraxs remember the envelop parameter receives a tuple, therefore this part is failing because the pattern matching, please change this part like this:
```suggestion
  @spec execute_transaction(
          tx_envelope :: tx_envelope(),
          public_key :: public_key(),
          secret_key :: secret_key()
        ) ::
          {:error, Horizon.Error.t()}
          | {:ok, AccountResponse.t()}
  defp execute_transaction({:ok, envelope}, public_key, secret_key) do
```

2022-10-24 16:38 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  defp(funder_key_pair_from_system) do
@Odraxs why did you use parentheses for the function definition?

2022-10-24 19:10 UTC, Odraxs commented
> @Odraxs FYI the tests for this module are being mocked, therefore is necessary to test the results using the implemented endpoints and review the operations of your master account in the Stellar Expert, to watch easiest the transactions created. I drop an [example of my master account](https://stellar.expert/explorer/testnet/account/GBF2MB6MFY52Z7OPKHFBIOBE5JOUOZH4NI6AWVC3CRPTGETT3Q7BNK63).
> 
> Please review our [documentation to create an account](https://docs.mintacoin.co/#create-account), and I left with you an example using cURL in my local instance:
> 
> ```shell
> curl -X POST -H \
>     -H  'authorization: yourapitoken' \
>     -H 'Content-Type: application/json' \
>     -d '{"blockchain": "stellar"}' \
>     "http://localhost:4000/accounts"
> ```
> 
> In case of any error review the table `oban_jobs` within your DB, and the field `errors`.


@SanGeeky So I just run the project locally and try the Post request to check if works properly ?

2022-10-24 19:53 UTC, SanGeeky commented
@Odraxs Of course, you should test locally that everything is working properly (tests, code format, functionality, etc). Take into account checking if your code works properly to make possible an efficient review.

2022-10-26 00:11 UTC, SanGeeky requested changes

2022-10-26 00:11 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +  @spec funder_account_information :: funder_account_information()
@Odraxs add parentheses here in the function name.

2022-10-26 00:11 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +          | create_account()
@Odraxs for now just left the type `create_account()`

2022-10-26 00:11 UTC, SanGeeky commented on lib/mintacoin/accounts/crypto/stellar.ex
> +          | {:ok, AccountResponse.t()}
@Odraxs refactor this to a type like this:

`  @type operation :: {:ok, AccountResponse.t()} | error()`

Please also update the resulting type of the function `format_response/3`

2022-10-26 15:53 UTC, SanGeeky approved these changes
Thank you for contributing, hope you learned more about Elixir.

2022-10-26 15:54 UTC, merged