85 refactor test
kommitters/mintacoin pull request #86
Opened 2022-06-23 16:13 UTC by santiagoboterokommit

## Description

Related to #85

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] Add factory for blockchain and change tests for assets
- [x] Add factory for payment and change tests for payments
- [ ] Move invalid values from code to set up, in accounts tests

2022-06-24 15:34 UTC, miguelnietoa requested changes
Good refactor! 💯 Some comments were added, check them out!

2022-06-24 15:34 UTC, miguelnietoa commented on apps/mintacoin/test/mintacoin/accounts/accounts_test.exs
>      end
What if instead of hardcoding `%{name: "Another name"}` in the test case, we move that map into the setup under a key like `valid_attrs`?

Same for the test case "with blank required fields", `%{name: "", email: ""}` can be moved into the setup under a key `invalid_attrs`, even we could replace `%{name: "", email: ""}` by just `%{}`.

2022-06-24 19:51 UTC, miguelnietoa approved these changes

2022-06-24 19:52 UTC, miguelnietoa commented
Hey @einerzg, could you please give us a second review?

2022-06-26 03:23 UTC, einerzg approved these changes
LGFM

2022-06-27 14:06 UTC, merged