Draft PR
kommitters/mintacoin pull request #90
Opened 2022-06-23 21:10 UTC by CristhianRodriguezMolina

## Description

Fixes #89

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-24 22:47 UTC, einerzg approved these changes
🦾

2022-06-25 01:02 UTC, miguelnietoa reviewed
Nice job, guys! 👌🏻 
Just a comment. ⬇️

2022-06-27 14:05 UTC, miguelnietoa requested changes

2022-06-27 14:05 UTC, miguelnietoa commented on apps/mintacoin_web/lib/mintacoin_web/views/payments_view.ex
> +  end
I think the `id` should be returned, as it is necessary for the `GET /payments/:id`

2022-06-27 14:05 UTC, miguelnietoa commented on apps/mintacoin_web/test/mintacoin_web/controllers/payments_controller_test.exs
> +      } = insert(:payment)
```suggestion
      %Payment{
        id: payment_id,
        source: source,
        destination: destination,
        asset_code: asset_code,
        amount: amount
      } = insert(:payment)
```

2022-06-27 14:42 UTC, miguelnietoa approved these changes
Awesome! 🚀 Thanks

2022-06-27 14:43 UTC, merged