Implement the customer's database boundaries and functions
kommitters/mintacoin pull request #91
Opened 2022-10-25 22:43 UTC by samu975

## Description

-     Create the schema for assets.
-     Create the customer functions that allow creating a new customer, and retrieving their account info by its id.
-     Create the respective migration.
-     Add the secret token generation
-     Use the encryption functions for the secret token.
-     Add the retrieve by customer id in the accounts functions.

Closes #85 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-28 23:02 UTC, SanGeeky requested changes
@FelipeGuzmanSierra @samu975 Nice implementation, Let's update the name of the contexts.

2022-10-31 22:46 UTC, SanGeeky requested changes

2022-10-31 22:46 UTC, SanGeeky commented on lib/mintacoin/customers/customers.ex
> +  @token_age 7 * 24 * 3600
@samu975 @FelipeGuzmanSierra Let's update the time of the token to 100 days.

2022-10-31 22:46 UTC, SanGeeky commented on lib/mintacoin/customers/customers.ex
> +
@samu975 @FelipeGuzmanSierra remove this line.

2022-10-31 22:46 UTC, SanGeeky commented on lib/mintacoin/customers/customers.ex
> +       Application.get_env(:mintacoin, :signing_salt)}
@samu975 @FelipeGuzmanSierra update this function using `do ... end`

2022-10-31 22:46 UTC, SanGeeky commented on priv/repo/migrations/20221024223648_create_api_keys.exs
> +    create(unique_index(:customers, :account_id, name: :account_id_api_key_index))
@samu975 @FelipeGuzmanSierra remove the opt for naming the index.

2022-10-31 22:46 UTC, SanGeeky commented on test/mintacoin/accounts/accounts_test.exs
> +    test "when customer doesn't exist", %{not_found_uuid: not_found_uuid} do
@samu975 @FelipeGuzmanSierra please update the test names as:

> when customer id exists
> when the customer doesn't exist

2022-10-31 22:46 UTC, SanGeeky commented on test/mintacoin/customers/customers_test.exs
> +  describe "create/1" do
@samu975 @FelipeGuzmanSierra add the test cases for "missing params".

2022-10-31 22:46 UTC, SanGeeky commented on lib/mintacoin/customers/customer.ex
> +    cast(customer, changes, [:encrypted_api_key, :name])
@samu975 @FelipeGuzmanSierra why you did not add validations for this changeset?

2022-11-01 15:21 UTC, samu975 commented on lib/mintacoin/customers/customers.ex
> +
Hello David, we need this line for the changeset. Why did you want to delete it?

2022-11-01 19:54 UTC, FelipeGuzmanSierra commented on lib/mintacoin/customers/customer.ex
> +    cast(customer, changes, [:encrypted_api_key, :name])
Hello @SanGeeky, we did not add the validations because in this case, we want the possibility to update one of the two parameters (name or encrypted_api_key), so we only cast if some of the two options changed.

2022-11-03 22:44 UTC, SanGeeky commented
This PR will be closed due to a new approach required in the Issue #85.

2022-11-03 22:44 UTC, closed without merging