68 Create Wallets' boundaries and tests
kommitters/mintacoin pull request #91
Opened 2022-06-23 23:22 UTC by MrJuanGaviriaK

Closes #68 

## Description

Implement the Wallets' boundaries and tests.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-24 16:06 UTC, miguelnietoa requested changes
Very good job @MrJuanGaviriaK 💯 

Please, address the requested changes and that's it!

2022-06-24 16:06 UTC, miguelnietoa commented on apps/mintacoin/test/mintacoin/wallets/wallets_test.exs
> +  alias Blockchains.Network
```suggestion
  alias Mintacoin.{Repo, Wallet, Wallets, Account, Accounts, Blockchain, Blockchains, Blockchains.Network}
```

2022-06-24 21:33 UTC, MrJuanGaviriaK commented on apps/mintacoin/lib/mintacoin/wallets/wallets.ex
> +  def retrieve_by_account_id(account_id), do: retrieve_by(account_id: account_id)
I'm going to fix it! Thanks.

2022-06-27 14:20 UTC, miguelnietoa requested changes

2022-06-27 14:20 UTC, miguelnietoa commented on apps/mintacoin/lib/mintacoin/wallets/wallets.ex
> +  @type blockchain_id :: String.t()
```suggestion
  @type account_id :: UUID.t()
  @type blockchain_id :: UUID.t()
```

2022-06-27 21:13 UTC, miguelnietoa approved these changes

2022-06-27 21:13 UTC, merged