98 Stellar implemantation
kommitters/mintacoin pull request #99
Opened 2022-06-30 17:29 UTC by miguelnietoa

## Description
This PR just create the boundaries for Stellar and the Stellar implementation itsself using the Crypto behaviour.

Fixes #98 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-30 22:32 UTC, juanhurtado10 requested changes

2022-06-30 22:32 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/crypto/stellar/assets.ex
> +     %Stellar.Horizon.Transaction{
@miguelnietoa @CristhianRodriguezMolina We should return here a Mintacoin struct, please do not forget the system knows nothing about internal implementations or blockchain's responses.

2022-07-01 19:31 UTC, juanhurtado10 requested changes

2022-07-01 19:31 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
> +       tx_json: %{
@miguelnietoa @CristhianRodriguezMolina is this attribute storing a JSON or a map?

2022-07-01 19:42 UTC, CristhianRodriguezMolina commented on apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
> +       tx_json: %{
Is storing a JSON, so we can use `Jason` to encode the map into something like this: `"{\"hello\":\"world\"}"`

2022-07-01 19:52 UTC, juanhurtado10 commented on apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
> +       tx_json: %{
OK great, please name it `tx_json` if you're planning to store a JSON or `raw_tx` if the content is a map.

2022-07-01 20:02 UTC, CristhianRodriguezMolina commented on apps/mintacoin/lib/mintacoin/crypto/stellar/accounts.ex
> +       tx_json: %{
Ok we will rename it to `raw_tx`.

2022-07-01 20:16 UTC, juanhurtado10 approved these changes

2022-07-01 20:18 UTC, merged